# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Mihir Surlaker's Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Mihir Surlaker
headline: Mechanical Engineering Student at WPI
description: >- # dont remove this line. this will ignore all new lines until the next section
  Aspiring mechanical engineer passionate about robotics, 
  building, and designing innovative solutions to real-world 
  challenges through teamwork and creativity.

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/avatar.jpeg


# Link your resume
# You can place your resume in assets/resume/{resume file.pdf} or add external link such as pdf saved in google drive 
resume-url: https://www.linkedin.com/in/mihir-surlaker


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: www.linkedin.com/in/mihir-surlaker   # https://www.linkedin.com/in/{your url slug}
             # https://bsky.app/profile/{your url slug}
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: 3D Modeling
    tools:
    - Onshape
    - Solidworks
    - Fusion 360 (Autodesk)
    - Blender (for complex shapes or animations)
  - category: Prototyping
    tools:
    - CNC
    - FDM
    - Arduino / Raspberry Pi
    - Breadboarding for circuit testing


# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   https://formspree.io/f/{8-digit key}



# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "#2d2d2d"
  border: "#f3d5c0"
  link: "#f28482"
  highlight: "#f6bd60"
  background: "#fff7f0"
  light_background: "#fffcf7"








#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
